[[SBML]]
arch = "aarch64"
git-tree-sha1 = "b4e1efa37a558f8ee12ec367628b4421e63687ef"
os = "macos"

    [[SBML.download]]
    sha256 = "8c0fc6856fdfd2d2cb624cf8fa3551961309c1b0d26b1b106f2ea25756a1b10b"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.aarch64-apple-darwin.tar.gz"
[[SBML]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b731375ae42f0d447c6ee07c7f0264e23e6108b5"
libc = "glibc"
os = "linux"

    [[SBML.download]]
    sha256 = "cf0e4cd605b63a913cef3bf3dfbbdf53c917cf97392ef02049388073c8c2e5b1"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SBML]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66ab2c3630b42e909f30c8242874d95761c3b82b"
libc = "musl"
os = "linux"

    [[SBML.download]]
    sha256 = "a254ef89bec6e77443765fa240fb86aa7d0753fcb685fe99c351f6f0c6a90f53"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.aarch64-linux-musl-cxx11.tar.gz"
[[SBML]]
arch = "aarch64"
git-tree-sha1 = "aa2e5f6f825437a9dc3ee9cef48075094401fa3e"
os = "freebsd"

    [[SBML.download]]
    sha256 = "1b5cccc7573f9266badbbc20e60f036a178c445bf4bfcc3b0feb06948dbc285f"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.aarch64-unknown-freebsd.tar.gz"
[[SBML]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a984c087aa463d9ee889ff53a1e8a04ffd69ed1d"
libc = "glibc"
os = "linux"

    [[SBML.download]]
    sha256 = "6deb81cb49070d9f6cb97b217c2650f5721752b7c88cc97de6b9eca93fef33c9"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SBML]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aac498e7b0d6d3e8e6d3c9bcba2fe57f79665db6"
libc = "musl"
os = "linux"

    [[SBML.download]]
    sha256 = "550df29b76a9947ab80b9ae662c7aa1e2236a07cc48612174a4d03953fdef942"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SBML]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb7db833def32defe66ce6e834f4b5b30ed4f1a9"
libc = "glibc"
os = "linux"

    [[SBML.download]]
    sha256 = "8481ac714352636cb96dbabd12cc77d6e336946e145ad4f4e58468d760ceca69"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SBML]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2327c38eb72d27d1459a50a6d1d7403d461ffa63"
libc = "musl"
os = "linux"

    [[SBML.download]]
    sha256 = "29b96bd02cbf9c9a1731e2808899fea889cef3ef268a6f41d5fbd47c757fb742"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SBML]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1c8ec8fff9fed673066f05579492e50de767a22"
libc = "glibc"
os = "linux"

    [[SBML.download]]
    sha256 = "96eabf92430d0163bd03f2020fa66307cfb8531869341cf2ec2d71c18daea780"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.i686-linux-gnu-cxx11.tar.gz"
[[SBML]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e25c5b788ca759403f46fd4d4d0ffaf20822550"
libc = "musl"
os = "linux"

    [[SBML.download]]
    sha256 = "077d0723674114099bd3f0bc4fef1af84e989f232372bb5b8de6914074d13365"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.i686-linux-musl-cxx11.tar.gz"
[[SBML]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8971b116d3c7771a58ce0b2f21704e448233e88a"
os = "windows"

    [[SBML.download]]
    sha256 = "eca2060706cc0bc547471a01de885fd4b2ee2dfbd91799cc94336882bb0b8b16"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.i686-w64-mingw32-cxx11.tar.gz"
[[SBML]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b215ca48ef2d682b33bfce05efc3df50e917bf1a"
libc = "glibc"
os = "linux"

    [[SBML.download]]
    sha256 = "e184d23717e88993bbf4e6b6cd321d71999e3aecf361ddd1811a20ec9b797d28"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SBML]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db19a9f1e38db943f22bea98310515dc53340403"
libc = "glibc"
os = "linux"

    [[SBML.download]]
    sha256 = "a82a0349fe8e34ce63445f72a77aabab8ba58a64e2ff64ec46206f44244b6920"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.riscv64-linux-gnu-cxx11.tar.gz"
[[SBML]]
arch = "x86_64"
git-tree-sha1 = "c6ee4149ac69fa6a4e615ba01bd25407dbd61cab"
os = "macos"

    [[SBML.download]]
    sha256 = "9af97ba084cd95b5f04bfab4bd9df3c131f8701659371e82e0e1ef6a2c185a9c"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.x86_64-apple-darwin.tar.gz"
[[SBML]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a5706a5d37a14e47a483953d63cfd25627d3e0e"
libc = "glibc"
os = "linux"

    [[SBML.download]]
    sha256 = "90ad1578f5ad1b30338e63c37e02900ae9f8715266cb062123f4cba10bc321ec"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SBML]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7d297cf5016ae172b0ed00a6951d68feb8651e3"
libc = "musl"
os = "linux"

    [[SBML.download]]
    sha256 = "649e2ab783d8ead05c37ded41c81ee73c6c1f877aee527132d07ec2c02f8c550"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.x86_64-linux-musl-cxx11.tar.gz"
[[SBML]]
arch = "x86_64"
git-tree-sha1 = "1ce67f80701369c2ca13ea26beb96f507e8e326c"
os = "freebsd"

    [[SBML.download]]
    sha256 = "64a48b67ac1012b163050c84825de075e31705f1d6c7ae1492d86f509eb799a9"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.x86_64-unknown-freebsd.tar.gz"
[[SBML]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bdb29c94abacfb768f6c5e29d8411702d25a7a2"
os = "windows"

    [[SBML.download]]
    sha256 = "9bb7fdf996eef16e0bb920c74c9f84fb6d83ebf47e73ea9cec5e4f22771dd6d2"
    url = "https://github.com/JuliaBinaryWrappers/SBML_jll.jl/releases/download/SBML-v5.21.0+0/SBML.v5.21.0.x86_64-w64-mingw32-cxx11.tar.gz"
